version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: bookquest-db
    restart: always
    ports:
      - "5434:5432" 
    environment:
      POSTGRES_USER: bookquest_user
      POSTGRES_PASSWORD: bookquest_pass
      POSTGRES_DB: bookquest
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
